'use strict';
const $=s=>document.getElementById(s),nf=new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}),df=new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}),pf=new Intl.NumberFormat('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2}),dt=s=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'));
const C={gold:'#ad760c',ihsg:'#2873b9',usd:'#8057ae'},names={gold:'Harga emas',ihsg:'IHSG',usd:'USD/IDR'},units={gold:'Rupiah per gram',ihsg:'Poin indeks',usd:'Rupiah per US$1'};
let dataset,tab='history',stage='masalah',rows=[],page=0,cursorH,cursorF,cursorOverview;
const money=v=>'Rp'+nf.format(v),format=(v,k)=>k==='gold'?money(v):k==='usd'?'Rp'+df.format(v):df.format(v)+' poin';
const avg=a=>a.reduce((s,v)=>s+v,0)/a.length;
function spark(values,color){let lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1;return `<svg viewBox="0 0 220 34" aria-hidden="true"><path d="${values.map((v,i)=>(i?'L':'M')+(i/Math.max(1,values.length-1)*220).toFixed(1)+','+(30-(v-lo)/span*26).toFixed(1)).join(' ')}" fill="none" stroke="${color}" stroke-width="1.6"/></svg>`;}
function kpi(label,value,note,values,color){return `<article class="kpi"><span class="label">${label}</span><strong>${value}</strong><small>${note}</small>${values?spark(values,color):''}</article>`;}
function chart(id,data,series,options={}){const svg=$(id),W=960,H=id==='errorChart'?290:340,L=82,R=20,T=20,B=42,iw=W-L-R,ih=H-T-B;
 let values=series.flatMap(s=>data.map(r=>s.fn(r))),lo=Math.min(...values),hi=Math.max(...values);if(options.zero){lo=Math.min(lo,0);hi=Math.max(hi,0);}let pad=(hi-lo)*.12||1;lo-=pad;hi+=pad;
 const ts=data.map(r=>new Date(r.date+'T00:00:00Z').getTime()),span=ts.at(-1)-ts[0],x=i=>span?L+(ts[i]-ts[0])/span*iw:L+iw/2,y=v=>T+(hi-v)/(hi-lo)*ih;
 let out='';for(let j=0;j<=4;j++){let v=lo+(hi-lo)*j/4,yy=y(v);out+=`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" stroke="#e1e7ef"/><text x="${L-10}" y="${yy+4}" text-anchor="end">${options.format?options.format(v):nf.format(v)}</text>`;}
 const ticks=[...new Set([0,Math.floor((data.length-1)/2),data.length-1])];ticks.forEach((i,j)=>out+=`<text x="${x(i)}" y="${H-10}" text-anchor="${j===0?'start':j===ticks.length-1?'end':'middle'}">${dt(data[i].date)}</text>`);
 if(options.zero)out+=`<line x1="${L}" x2="${W-R}" y1="${y(0)}" y2="${y(0)}" stroke="#7e90a2" stroke-width="1.2"/>`;
 series.forEach(s=>{out+=`<path d="${data.map((r,i)=>(i?'L':'M')+x(i).toFixed(2)+','+y(s.fn(r)).toFixed(2)).join(' ')}" stroke="${s.color}" fill="none" stroke-width="2.3" ${s.dash?'stroke-dasharray="7 5"':''}/>`;if(data.length===1)out+=`<circle cx="${x(0)}" cy="${y(s.fn(data[0]))}" r="4" fill="${s.color}"/>`;});out+='<g class="crosshair"></g>';svg.innerHTML=out;
 const cross=svg.querySelector('.crosshair');const move=i=>{cross.innerHTML=`<line x1="${x(i)}" x2="${x(i)}" y1="${T}" y2="${H-B}" stroke="#9eacbb" stroke-dasharray="3 4"/>`+series.map(s=>`<circle cx="${x(i)}" cy="${y(s.fn(data[i]))}" r="4" fill="${s.color}" stroke="white" stroke-width="1.5"/>`).join('');};
 svg.onpointermove=e=>{const rect=svg.getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*W;let idx=0,best=Infinity;data.forEach((r,i)=>{let d=Math.abs(x(i)-px);if(d<best){best=d;idx=i;}});options.onCursor?.(idx);move(idx);};return move;
}
function hRead(i){let r=rows[i],mode=$('variable').value;$('historyCursor').value=i;$('historyReadout').innerHTML=`<b>${dt(r.date)}</b>`+(mode==='indexed'?['gold','ihsg','usd'].map(k=>`<span style="color:${C[k]}">${names[k]} ${df.format(r[k]/rows[0][k]*100)}</span>`).join(''):`<span style="color:${C[mode]}">${format(r[mode],mode)}</span>`);cursorH?.(i);}
function fRead(i){let r=rows[i];$('forecastCursor').value=i;$('forecastReadout').innerHTML=`<b>${dt(r.date)}</b><span style="color:${C.ihsg}">Aktual ${money(r.actual)}</span><span style="color:${C.gold}">Prediksi ${money(r.prediction)}</span><span>Selisih ${r.prediction>=r.actual?'+':'−'}${money(Math.abs(r.prediction-r.actual))}</span>`;cursorF?.(i);}
function history(){let first=rows[0],last=rows.at(-1),change=(last.gold/first.gold-1)*100;$('historyKpis').innerHTML=['gold','ihsg','usd'].map(k=>kpi(names[k],format(last[k],k),'Nilai akhir · '+dt(last.date),rows.map(r=>r[k]),C[k])).join('')+kpi('Perubahan emas',(change>=0?'+':'')+pf.format(change)+'%',rows.length+' observasi · akhir vs. awal');let mode=$('variable').value,keys=mode==='indexed'?['gold','ihsg','usd']:[mode];$('historyUnits').textContent=mode==='indexed'?'Indeks 100 pada awal rentang terpilih':units[mode];$('historyLegend').innerHTML=keys.map(k=>`<span style="--c:${C[k]}">${names[k]}</span>`).join('');cursorH=chart('historyChart',rows,keys.map(k=>({color:C[k],fn:r=>mode==='indexed'?r[k]/first[k]*100:r[k]})),{format:v=>mode==='gold'?df.format(v/1e6)+' jt':nf.format(v),onCursor:hRead});$('historyCursor').max=rows.length-1;hRead(rows.length-1);let k=mode==='indexed'?'gold':mode,v=rows.map(r=>r[k]);$('summaryTitle').textContent=names[k];$('summaryStats').innerHTML=[['Terendah',format(Math.min(...v),k)],['Tertinggi',format(Math.max(...v),k)],['Rata-rata',format(avg(v),k)],['Observasi',nf.format(rows.length)]].map(([a,b])=>`<div class="stat-row"><span>${a}</span><strong>${b}</strong></div>`).join('');let ch=(last[k]/first[k]-1)*100;$('historyInsight').textContent=`${names[k]} ${ch>=0?'naik':'turun'} ${pf.format(Math.abs(ch))}% dari awal ke akhir rentang ini. Perubahan ini bukan ukuran volatilitas harian.`;$('historyFootnote').textContent=`${dt(first.date)}–${dt(last.date)} · ${rows.length} observasi. ${mode==='indexed'?'Indeks dinormalisasi ulang saat rentang berubah.':'Skala vertikal disesuaikan dengan rentang nilai.'} Sumbu waktu memakai tanggal kalender; hari tanpa observasi tidak ditambahkan.`;}
function forecast(){const e=rows.map(r=>r.prediction-r.actual),mae=avg(e.map(Math.abs)),rmse=Math.sqrt(avg(e.map(v=>v*v))),mape=avg(rows.map((r,i)=>Math.abs(e[i]/r.actual)))*100;$('forecastKpis').innerHTML=kpi('MAPE',pf.format(mape)+'%','Rata-rata kesalahan persentase absolut')+kpi('MAE',money(mae),'Rata-rata selisih absolut per gram')+kpi('RMSE',money(rmse),'Lebih peka terhadap kesalahan besar')+kpi('Observasi evaluasi',nf.format(rows.length),dt(rows[0].date)+'–'+dt(rows.at(-1).date));cursorF=chart('forecastChart',rows,[{color:C.ihsg,fn:r=>r.actual},{color:C.gold,fn:r=>r.prediction,dash:true}],{format:v=>df.format(v/1e6)+' jt',onCursor:fRead});$('forecastCursor').max=rows.length-1;fRead(rows.length-1);chart('errorChart',rows,[{color:'#b85e55',fn:r=>r.prediction-r.actual}],{zero:true,format:v=>nf.format(v/1000)+' rb'});$('forecastInsight').textContent=`Pada ${rows.length} observasi terpilih, rata-rata selisih absolut adalah ${money(mae)} per gram dan MAPE ${pf.format(mape)}%. Angka ini hanya merangkum periode yang sedang ditampilkan.`;}
function table(){const evalMode=tab==='forecast',cols=evalMode?['Tanggal','Aktual (Rp/gram)','Prediksi (Rp/gram)','Selisih (Rp/gram)','Kesalahan absolut (%)']:['Tanggal','Emas (Rp/gram)','IHSG (poin)','USD/IDR (Rp/US$)'];$('dataHead').innerHTML='<tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'</tr>';const subset=rows.slice(page*10,page*10+10);$('dataBody').innerHTML=subset.map(r=>'<tr><td>'+dt(r.date)+'</td>'+(evalMode?[nf.format(r.actual),nf.format(r.prediction),df.format(r.prediction-r.actual),pf.format(Math.abs((r.prediction-r.actual)/r.actual)*100)]:[nf.format(r.gold),df.format(r.ihsg),df.format(r.usd)]).map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('');$('tableCount').textContent=rows.length+' observasi · menampilkan 10 baris per halaman';$('pageInfo').textContent=`Halaman ${page+1} dari ${Math.max(1,Math.ceil(rows.length/10))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*10>=rows.length;}
function render(){if(tab==='dynamics')return;const base=dataset[tab];rows=base.filter(r=>r.date>=$('start').value&&r.date<=$('end').value);page=0;if(!rows.length){$('rangeError').textContent='Tidak ada observasi dalam rentang ini. Pilih rentang lain.';$('rangeError').hidden=false;return;} $('rangeError').hidden=true;if(tab==='history')history();else forecast();table();}
function rangeReset(){const base=dataset[tab];for(const id of ['start','end']){$(id).min=base[0].date;$(id).max=base.at(-1).date;}$('start').value=base[0].date;$('end').value=base.at(-1).date;document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('selected',b.dataset.range==='all'));render();}
function switchTab(t){tab=t;$('rangeError').hidden=true;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===tab));for(const key of ['history','forecast','dynamics'])$(key+'Panel').hidden=key!==tab;$('timeControls').hidden=tab==='dynamics';$('tableCard').hidden=tab==='dynamics';const titles={history:['Karakteristik pergerakan data','Tujuan 1: memahami karakteristik pergerakan harga emas, IHSG, dan USD/IDR.'],dynamics:['Respons dinamis dan kontribusi guncangan','Tujuan 2: menganalisis respons harga emas dan kontribusi sumber guncangan melalui IRF dan FEVD.'],forecast:['Peramalan harga emas dan evaluasinya','Tujuan 3: melakukan peramalan emas dengan informasi emas, IHSG, dan USD/IDR dalam pendekatan multivariat.']};$('resultLabel').textContent='HASIL TUJUAN '+({history:1,dynamics:2,forecast:3}[tab]);$('resultMethod').textContent=({history:'Analisis deskriptif dan visualisasi deret waktu.',dynamics:'IRF dan FEVD dari model VECM; uji Granger melengkapi informasi hubungan prediktif.',forecast:'Peramalan 90 periode menggunakan VECM, lalu evaluasi MAE, RMSE, dan MAPE terhadap nilai aktual.'}[tab]);$('pageTitle').textContent=titles[tab][0];$('pageSubtitle').textContent=titles[tab][1];if(tab!=='dynamics')rangeReset();}
function drawFEVD(){
 const W=960,H=310,L=60,R=15,T=22,B=50,iw=W-L-R,ih=H-T-B,step=iw/20,bw=step*.78;let out='';
 for(let v=0;v<=100;v+=25){const y=T+ih*(1-v/100);out+=`<line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" stroke="#dce2e8"/><text x="${L-10}" y="${y+4}" text-anchor="end">${v}%</text>`;}
 dataset.fevd.forEach((r,i)=>{let used=0,sum=r.gold+r.ihsg+r.usd,x=L+i*step+(step-bw)/2;out+=`<g data-fevd-horizon="${r.horizon}">`;[['gold','#4c4c4c'],['ihsg','#b8b8b8'],['usd','#ffffff']].forEach(([k,c])=>{let height=r[k]/sum*ih,y=T+ih-used-height;out+=`<rect x="${x}" y="${y}" width="${bw}" height="${height}" fill="${c}" stroke="#333333" stroke-width=".7"/>`;used+=height;});out+=`<rect class="fevd-hit" x="${x-3}" y="${T}" width="${bw+6}" height="${ih}" fill="transparent"/><text x="${x+bw/2}" y="${H-B+21}" text-anchor="middle">${r.horizon}</text></g>`;});
 out+=`<text x="${L+iw/2}" y="${H-4}" text-anchor="middle">Horizon (periode)</text><g id="fevdSelection"></g>`;$('fevdChart').innerHTML=out;
 $('fevdChart').querySelectorAll('[data-fevd-horizon]').forEach(g=>{const read=()=>{$('horizon').value=g.dataset.fevdHorizon;fevd();};g.addEventListener('pointerenter',read);g.addEventListener('click',read);});
}
function fevd(){const h=Number($('horizon').value),r=dataset.fevd.find(r=>r.horizon===h),vals=[r.gold,r.ihsg,r.usd],labels=['Emas sendiri','IHSG','USD/IDR'],cs=['#4c4c4c','#777777','#555555'];$('fevdNumbers').innerHTML=vals.map((v,i)=>`<div style="color:${cs[i]}"><strong>${new Intl.NumberFormat('id-ID',{minimumFractionDigits:3,maximumFractionDigits:3}).format(v)}%</strong><span>${labels[i]}</span></div>`).join('');$('fevdInsight').textContent=`Horizon ${h} periode: kontribusi emas sendiri ${df.format(r.gold)}%, USD/IDR ${df.format(r.usd)}%, dan IHSG ${df.format(r.ihsg)}%. Hasil bergantung pada spesifikasi dan identifikasi guncangan model.`;const L=60,step=(960-60-15)/20;$('fevdSelection').innerHTML=`<rect x="${L+(h-1)*step+1}" y="19" width="${step-2}" height="244" fill="none" stroke="#2873b9" stroke-width="2" pointer-events="none"/>`;$('fevdChart').setAttribute('aria-label',`FEVD emas pada horizon 1–20. Horizon terpilih ${h}: emas ${r.gold}%, IHSG ${r.ihsg}%, USD/IDR ${r.usd}%.`);}
function csv(){const evalMode=tab==='forecast',head=evalMode?['Tanggal','Aktual_Rp_per_gram','Prediksi_Rp_per_gram','Selisih_Rp_per_gram','Kesalahan_absolut_persen']:['Tanggal','Emas_Rp_per_gram','IHSG_poin','USDIDR_Rp_per_USD'];const lines=[head.join(','),...rows.map(r=>(evalMode?[r.date,r.actual,r.prediction,r.prediction-r.actual,Math.abs((r.prediction-r.actual)/r.actual)*100]:[r.date,r.gold,r.ihsg,r.usd]).join(','))];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download=`emas_${tab}_${rows[0].date}_${rows.at(-1).date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showStage(key){stage=key;for(const id of ['masalah','tujuan','metode','hasil','simpulan'])$(id).hidden=id!==key;document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.stage===key));$('rangeError').hidden=true;$('stageCaption').textContent=({masalah:'Permasalahan: apa yang ingin dijawab oleh penelitian?',tujuan:'Tujuan: hasil apa yang ingin dicapai untuk menjawab setiap masalah?',metode:'Metode: bagaimana data dan model digunakan untuk menjawab tujuan?',hasil:'Hasil: pilih tujuan, telusuri grafik, lalu baca pembahasannya.',simpulan:'Kesimpulan: apa jawaban akhir untuk ketiga tujuan penelitian?'}[key]);if(key==='hasil'){switchTab(tab);}else{['historyPanel','forecastPanel','dynamicsPanel','timeControls','tableCard'].forEach(id=>$(id).hidden=true);}window.scrollTo({top:0,behavior:'auto'});}
function overviewRead(i){const r=dataset.history[i];$('overviewCursor').value=i;$('overviewReadout').innerHTML=`<b>${dt(r.date)}</b><span style="color:${C.gold}">${money(r.gold)} per gram</span>`;cursorOverview?.(i);}
(window.RESEARCH_DATA ? Promise.resolve(window.RESEARCH_DATA) : fetch('data.json').then(r=>{if(!r.ok)throw Error();return r.json();})).then(d=>{dataset=d;$('status').hidden=true;switchTab('history');drawFEVD();fevd();cursorOverview=chart('overviewChart',dataset.history,[{color:C.gold,fn:r=>r.gold}],{format:v=>df.format(v/1e6)+' jt',onCursor:overviewRead});overviewRead(721);$('overviewCursor').oninput=e=>overviewRead(+e.target.value);showStage('masalah');document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>showStage(b.dataset.stage)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();tab=b.dataset.open;showStage('hasil');}));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('apply').onclick=()=>{if(!$('start').value||!$('end').value||$('start').value>$('end').value){$('rangeError').textContent='Tanggal awal harus terisi dan tidak boleh melewati tanggal akhir.';$('rangeError').hidden=false;return;}const base=dataset[tab],candidate=base.filter(r=>r.date>=$('start').value&&r.date<=$('end').value);if(!candidate.length){$('rangeError').textContent='Tidak ada observasi dalam rentang tersebut. Grafik masih menunjukkan rentang sebelumnya.';$('rangeError').hidden=false;return;}document.querySelectorAll('[data-range]').forEach(b=>b.classList.remove('selected'));render();};document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const base=dataset[tab],last=base.at(-1).date;$('end').value=last;if(b.dataset.range==='all')$('start').value=base[0].date;else{let a=new Date(last+'T00:00:00Z');a.setUTCDate(a.getUTCDate()-Number(b.dataset.range));$('start').value=a.toISOString().slice(0,10)<base[0].date?base[0].date:a.toISOString().slice(0,10);}document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('selected',x===b));render();});$('variable').onchange=()=>{if(rows.length)history();};$('historyCursor').oninput=e=>hRead(+e.target.value);$('forecastCursor').oninput=e=>fRead(+e.target.value);$('horizon').onchange=fevd;$('prev').onclick=()=>{if(page>0){page--;table();}};$('next').onclick=()=>{if((page+1)*10<rows.length){page++;table();}};$('download').onclick=csv;}).catch(()=>{$('status').textContent='Data belum berhasil dimuat. Muat ulang halaman untuk mencoba kembali.';});
